### ISSUE TITLE
Connection Failed. MissingAuthenticationTokenException

### ISSUE THREAD

**Issue by davesiddons** [awslabs/dynamodb-shell#12]
**Describe the bug**
Full error is this when running ddbsh

ddbsh - version 0.6.1
[ddbsh.cpp, 188], Connection Failed. MissingAuthenticationTokenException. < a series of random letters and numbers >.
	Request is missing Authentication Token

**To Reproduce**
1. AWS credentials file looks like this (cut down and anonymised)

# management user - just for login and mfa association
[d-login]
aws_access_key_id = ……..
aws_secret_access_key = ……..

# management user with mfa, allows assuming roles
[default]
aws_access_key_id = …………
aws_secret_access_key = ……………..
aws_session_token = ……… (populated after login)

[d-development]
role_arn = arn:aws:iam::<acc_no>:role/administrator
source_profile = default

2. export AWS_PROFILE=d-development
3. test with "aws dynamodb list-tables;" which lists all table in the development account successfully
4. run ddbsh
5. See error

**Comment by amrith** [comment]
Thanks for your bug report. 

This looks like a manifestation of [this](https://github.com/aws/aws-sdk-cpp/issues/150) issue. I'll try and implement the workaround described there.

**Comment by damshenas** [comment]
+1

**Comment by damshenas** [comment]
Thanks for the effort. It works perfectly fine for me; not out of the box but when following the README instructions. 

It would be nice to follow the approach AWS CLI suggests (using the .aws/config instead of .aws/credentials) so it would work out of the box same as AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html 
But I am already happy with this PR.

**Comment by amrith** [comment]
@damshenas please let me know what doesn't work for you.

The code submitted (as in the PR) looks both at the config file and the credentials file, but it looks first at the credentials file.

If you have the profile in the credentials file and you run ddbsh -d to get debug log, you will see this in the debug log.

```
2024-02-23 10:35:50 (23356) [DEBUG] [ddbsh.cpp, 172] Using profile cross-acct
2024-02-23 10:35:50 (23356) [DEBUG] [ddbsh.cpp, 186] Looking for named credential profile. cross-acct
2024-02-23 10:35:50 (23356) [DEBUG] [ddbsh.cpp, 192] Found named credential profile. cross-acct
```

If on the other hand, you put it in the config file, you will see this.

```
2024-02-23 10:34:59 (23315) [DEBUG] [ddbsh.cpp, 172] Using profile cross-acct
2024-02-23 10:34:59 (23315) [DEBUG] [ddbsh.cpp, 186] Looking for named credential profile. cross-acct
2024-02-23 10:34:59 (23315) [DEBUG] [ddbsh.cpp, 205] Looking for named config profile. cross-acct
2024-02-23 10:34:59 (23315) [DEBUG] [ddbsh.cpp, 212] Found named config profile. cross-acct
```

In other words, if you configure it the way the doc says, it should work.

**Comment by amrith** [comment]
Specifically, I'd like to make it work out of the box. So I'm trying to understand the statement, "not out of the box but when following the README instructions".

Thank you

**Comment by damshenas** [comment]
I did test again with the -d option. For some reason it did not give me the debug info. But anyhow I think I figured why it did not work.

So when I tested the version 0.7, 

- at first, I relied on the config file as it is which the name of the profile is stored like [profile test1]. This did not work and gave me `[ddbsh.cpp, 299], Connection Failed. MissingAuthenticationTokenException.` which means the credential was not found.

- then, I tried with following the README, which suggest adding the role info in the credential file. I also noticed the profile name is defined like this: [test1] and not like the one in the config file [profile test1]. This worked which meant I have to change the credentials file.

- now, I test again by removing the role info from credentials file; and renaming the profile name in the config file to [test1] instead of the original [profile test1]. This time, it worked! It were able to pick up the role info.

So I think your PR is looking at the config file searching for [xyz] instead of [profile xyz]. I will check the code and see if I can find the corresponding lines but without looking at the code I think this is the issue.

Hope this helps :)

**Comment by amrith** [comment]
Interesting observation. I'm not parsing the file myself, you'll observe that I'm using this

```
  Aws::Config::AWSConfigFileProfileConfigLoader credLoader(
	Aws::Auth::ProfileConfigFileAWSCredentialsProvider::GetCredentialsProfileFilename());
```

and

```
Aws::Config::AWSConfigFileProfileConfigLoader configLoader(Aws::Auth::GetConfigProfileFilename());
```

I'm not natively parsing the configuration files. Let me check and see whether this is a known behavior, and whether this is a bug :(

See lines 180 and 201 in ddbsh.cpp

**Comment by amrith** [comment]
Looks like the error in my patch is that I didn't properly specify whether or not the profile has the "profile" prefix.

See here

https://sdk.amazonaws.com/cpp/api/LATEST/aws-cpp-sdk-core/html/class_aws_1_1_config_1_1_a_w_s_config_file_profile_config_loader.html#a77dd35f21c1aa750833a69dff1507b82

Here the documentation reads,

```
Aws::Config::AWSConfigFileProfileConfigLoader::AWSConfigFileProfileConfigLoader ( 
     const Aws::String &fileName, bool 	useProfilePrefix = false )

// useProfilePrefix - whether or not the profiles are prefixed with "profile", credentials file is not while the config file is. Defaults to off.
```

Thank you @damshenas for the thorough review.

**Comment by amrith** [comment]
@damshenas a new pull request is now available for you to test with.

**Comment by damshenas** [comment]
Ok recompiled and tested. Works perfectly fine now. I think this issue is resolved using this PR.
Thanks for the prompt response and the fix.

**Comment by amrith** [comment]
Thanks @damshenas for the review.

**Comment by frumpel** [comment]
Still having this problem on Mac - ddbsh 0.8.1 will not honor the AWS_PROFILE or AWS_DEFAULT_PROFILE setting. My workaround is to wrap the call into temp credentials like this 

Wrapper script `with-temp.sh`

```bash
#!/bin/bash

TOKEN_JSON=$( aws sts get-session-token --duration-seconds 3600 )
export AWS_ACCESS_KEY_ID=$( echo $TOKEN_JSON | jq -r '.Credentials.AccessKeyId' )
export AWS_SECRET_ACCESS_KEY=$( echo $TOKEN_JSON | jq -r '.Credentials.SecretAccessKey' )
export AWS_SESSION_TOKEN=$( echo $TOKEN_JSON | jq -r '.Credentials.SessionToken' )

echo "$@"
"$@"
```

Invocation

```bash
./with-temp.sh /opt/homebrew/bin/ddbsh
/opt/homebrew/bin/ddbsh
```
